export const BUILDINGS = {
  // Resource extraction
  farm: {
    id: 'farm',
    name: 'Farm',
    icon: '🌾',
    cost: { gold: 20, lumber: 1 },
    buildTime: 2,
    produces: { grain: 2 },
    validTerrain: ['plains', 'grassland', 'river', 'savanna'],
    maxPerTile: 1,
    description: 'Cultivates the land to produce grain',
  },
  ranch: {
    id: 'ranch',
    name: 'Ranch',
    icon: '🐄',
    cost: { gold: 30, lumber: 1 },
    buildTime: 2,
    produces: { cattle: 1 },
    validTerrain: ['grassland', 'plains', 'savanna'],
    maxPerTile: 1,
    description: 'Raises livestock for food and leather',
  },
  lumber_camp: {
    id: 'lumber_camp',
    name: 'Lumber Camp',
    icon: '🪓',
    cost: { gold: 15 },
    buildTime: 1,
    produces: { timber: 2 },
    validTerrain: ['forest', 'jungle'],
    maxPerTile: 1,
    description: 'Harvests timber from surrounding forests',
  },
  mine: {
    id: 'mine',
    name: 'Mine',
    icon: '⛏️',
    cost: { gold: 50, lumber: 2 },
    buildTime: 3,
    produces: { iron: 1, coal: 1 },
    validTerrain: ['hills', 'mountains'],
    maxPerTile: 1,
    description: 'Extracts minerals from the earth',
  },
  gold_mine: {
    id: 'gold_mine',
    name: 'Gold Mine',
    icon: '🥇',
    cost: { gold: 80, lumber: 2, steel: 1 },
    buildTime: 4,
    produces: { gold: 3 },
    validTerrain: ['hills', 'mountains', 'desert'],
    requiresResource: 'gold',
    maxPerTile: 1,
    description: 'Mines precious gold deposits',
  },
  oil_well: {
    id: 'oil_well',
    name: 'Oil Well',
    icon: '🛢️',
    cost: { gold: 100, steel: 2 },
    buildTime: 4,
    produces: { oil: 2 },
    validTerrain: ['desert', 'tundra', 'plains'],
    requiresResource: 'oil',
    requiresTech: 'oil_drilling',
    maxPerTile: 1,
    description: 'Extracts petroleum from underground reserves',
  },
  fishing_port: {
    id: 'fishing_port',
    name: 'Fishing Port',
    icon: '🎣',
    cost: { gold: 25, lumber: 1 },
    buildTime: 2,
    produces: { fish: 2 },
    validTerrain: ['coast', 'river'],
    maxPerTile: 1,
    description: 'Harvests fish from surrounding waters',
  },
  plantation: {
    id: 'plantation',
    name: 'Plantation',
    icon: '🌿',
    cost: { gold: 40, lumber: 1 },
    buildTime: 3,
    produces: { cotton: 2 },
    validTerrain: ['plains', 'grassland', 'savanna', 'jungle'],
    maxPerTile: 1,
    description: 'Grows cash crops for processing',
  },
  // Processing / Industry
  sawmill: {
    id: 'sawmill',
    name: 'Sawmill',
    icon: '🏭',
    cost: { gold: 40, iron: 1 },
    buildTime: 2,
    consumes: { timber: 2 },
    produces: { lumber: 2 },
    validTerrain: ['plains', 'grassland', 'forest', 'hills', 'river'],
    maxPerTile: 1,
    description: 'Processes raw timber into quality lumber',
  },
  foundry: {
    id: 'foundry',
    name: 'Foundry',
    icon: '🔥',
    cost: { gold: 80, stone: 2 },
    buildTime: 4,
    consumes: { iron: 2, coal: 1 },
    produces: { steel: 2 },
    validTerrain: ['plains', 'grassland', 'hills', 'river'],
    maxPerTile: 1,
    description: 'Smelts iron and coal into steel',
  },
  textile_mill: {
    id: 'textile_mill',
    name: 'Textile Mill',
    icon: '🧵',
    cost: { gold: 60, lumber: 2 },
    buildTime: 3,
    consumes: { cotton: 2 },
    produces: { textiles: 2 },
    validTerrain: ['plains', 'grassland', 'river'],
    maxPerTile: 1,
    description: 'Weaves raw cotton into fine textiles',
  },
  arms_factory: {
    id: 'arms_factory',
    name: 'Arms Factory',
    icon: '⚔️',
    cost: { gold: 120, steel: 2 },
    buildTime: 5,
    consumes: { steel: 1, timber: 1 },
    produces: { arms: 2 },
    validTerrain: ['plains', 'grassland', 'hills', 'river'],
    maxPerTile: 1,
    description: 'Manufactures weapons and military equipment',
  },
  // Infrastructure
  road: {
    id: 'road',
    name: 'Road',
    icon: '🛤️',
    cost: { gold: 10 },
    buildTime: 1,
    movementBonus: -0.5,
    validTerrain: ['plains', 'grassland', 'forest', 'hills', 'desert', 'tundra', 'swamp', 'savanna', 'river', 'jungle'],
    maxPerTile: 1,
    description: 'Improves movement speed across terrain',
  },
  railroad: {
    id: 'railroad',
    name: 'Railroad',
    icon: '🚂',
    cost: { gold: 40, steel: 1 },
    buildTime: 2,
    movementBonus: -1,
    resourceBonus: 1.5,
    requiresTech: 'railroads',
    validTerrain: ['plains', 'grassland', 'forest', 'hills', 'desert', 'savanna', 'river'],
    maxPerTile: 1,
    replacesBuilding: 'road',
    description: 'Dramatically improves transport and resource flow',
  },
  port: {
    id: 'port',
    name: 'Port',
    icon: '⚓',
    cost: { gold: 60, lumber: 2, stone: 1 },
    buildTime: 3,
    validTerrain: ['coast'],
    maxPerTile: 1,
    allowsNavalRecruitment: true,
    tradeBonus: 1.25,
    description: 'Enables naval construction and overseas trade',
  },
  fort: {
    id: 'fort',
    name: 'Fort',
    icon: '🏰',
    cost: { gold: 80, stone: 3, lumber: 2 },
    buildTime: 4,
    defenseBonus: 5,
    validTerrain: ['plains', 'grassland', 'forest', 'hills', 'desert', 'tundra', 'savanna', 'river'],
    maxPerTile: 1,
    description: 'Fortified position providing strong defensive bonus',
  },
  // Cities & Culture
  market: {
    id: 'market',
    name: 'Market',
    icon: '🏪',
    cost: { gold: 30, lumber: 1 },
    buildTime: 2,
    tradeBonus: 1.1,
    goldPerTurn: 3,
    validTerrain: ['plains', 'grassland', 'river', 'savanna', 'coast'],
    maxPerTile: 1,
    description: 'Local marketplace boosting trade and income',
  },
  university: {
    id: 'university',
    name: 'University',
    icon: '🎓',
    cost: { gold: 100, stone: 2, lumber: 2 },
    buildTime: 5,
    researchBonus: 3,
    requiresTech: 'education',
    validTerrain: ['plains', 'grassland', 'river'],
    maxPerTile: 1,
    description: 'Center of learning, accelerates research',
  },
  barracks: {
    id: 'barracks',
    name: 'Barracks',
    icon: '🏛️',
    cost: { gold: 50, lumber: 2 },
    buildTime: 3,
    allowsRecruitment: true,
    validTerrain: ['plains', 'grassland', 'hills', 'river', 'savanna'],
    maxPerTile: 1,
    description: 'Trains military units for your armies',
  },
  embassy: {
    id: 'embassy',
    name: 'Embassy',
    icon: '🏛️',
    cost: { gold: 60, stone: 1, lumber: 1 },
    buildTime: 3,
    diplomacyBonus: 5,
    validTerrain: ['plains', 'grassland', 'river'],
    maxPerTile: 1,
    description: 'Improves diplomatic relations with other nations',
  },
};

export const BUILDING_LIST = Object.values(BUILDINGS);
