export const EVENT_TYPES = {
  NATURAL_DISASTER: 'natural_disaster',
  ECONOMIC: 'economic',
  POLITICAL: 'political',
  MILITARY: 'military',
  DISCOVERY: 'discovery',
  CULTURAL: 'cultural',
};

export const RANDOM_EVENTS = [
  {
    id: 'gold_rush',
    name: 'Gold Rush!',
    type: EVENT_TYPES.DISCOVERY,
    icon: '🥇',
    description: 'Gold deposits have been discovered in {territory}! Prospectors flood the region.',
    probability: 0.03,
    effects: { addResource: { gold: 5 }, population: 1.1, stability: -3 },
    duration: 5,
    conditions: { hasTerrain: ['hills', 'mountains'] },
  },
  {
    id: 'bountiful_harvest',
    name: 'Bountiful Harvest',
    type: EVENT_TYPES.ECONOMIC,
    icon: '🌾',
    description: 'Perfect weather has led to an exceptional harvest across your farmlands.',
    probability: 0.06,
    effects: { resourceMultiplier: { grain: 2 }, stability: 3 },
    duration: 3,
    conditions: { hasBuilding: 'farm' },
  },
  {
    id: 'plague',
    name: 'Plague Outbreak',
    type: EVENT_TYPES.NATURAL_DISASTER,
    icon: '☠️',
    description: 'A terrible plague sweeps through {territory}, devastating the population.',
    probability: 0.02,
    effects: { population: 0.85, stability: -10, workerLoss: 0.15 },
    duration: 4,
    conditions: {},
  },
  {
    id: 'drought',
    name: 'Severe Drought',
    type: EVENT_TYPES.NATURAL_DISASTER,
    icon: '☀️',
    description: 'A prolonged drought has withered crops and dried rivers.',
    probability: 0.04,
    effects: { resourceMultiplier: { grain: 0.3, cattle: 0.5 }, stability: -5 },
    duration: 3,
    conditions: { hasTerrain: ['plains', 'grassland', 'desert', 'savanna'] },
  },
  {
    id: 'earthquake',
    name: 'Earthquake',
    type: EVENT_TYPES.NATURAL_DISASTER,
    icon: '🌋',
    description: 'A devastating earthquake rocks {territory}, damaging buildings.',
    probability: 0.02,
    effects: { buildingDamage: 0.3, stability: -8 },
    duration: 1,
    conditions: { hasTerrain: ['mountains', 'hills'] },
  },
  {
    id: 'trade_boom',
    name: 'Trade Boom',
    type: EVENT_TYPES.ECONOMIC,
    icon: '📈',
    description: 'International demand for your goods has surged. Trade revenues soar!',
    probability: 0.04,
    effects: { tradeMultiplier: 1.5, goldIncome: 20 },
    duration: 5,
    conditions: { hasBuilding: 'market' },
  },
  {
    id: 'market_crash',
    name: 'Market Crash',
    type: EVENT_TYPES.ECONOMIC,
    icon: '📉',
    description: 'Financial panic grips the markets. Trade values plummet.',
    probability: 0.03,
    effects: { tradeMultiplier: 0.5, goldIncome: -15, stability: -5 },
    duration: 4,
    conditions: {},
  },
  {
    id: 'rebellion',
    name: 'Popular Rebellion',
    type: EVENT_TYPES.POLITICAL,
    icon: '⚔️',
    description: 'Dissent erupts into open rebellion in {territory}!',
    probability: 0.02,
    effects: { spawnRebels: true, stability: -15, territoryloss: true },
    duration: 1,
    conditions: { stabilityBelow: 30 },
  },
  {
    id: 'great_thinker',
    name: 'Great Thinker Emerges',
    type: EVENT_TYPES.CULTURAL,
    icon: '🎓',
    description: 'A brilliant scholar emerges, advancing your scientific knowledge.',
    probability: 0.04,
    effects: { researchBonus: 15 },
    duration: 1,
    conditions: { hasBuilding: 'university' },
  },
  {
    id: 'diplomatic_incident',
    name: 'Diplomatic Incident',
    type: EVENT_TYPES.POLITICAL,
    icon: '😠',
    description: 'An incident with {randomNation} has soured diplomatic relations.',
    probability: 0.05,
    effects: { relationPenalty: -15 },
    duration: 1,
    conditions: {},
  },
  {
    id: 'military_genius',
    name: 'Military Genius',
    type: EVENT_TYPES.MILITARY,
    icon: '⭐',
    description: 'A gifted general rises through the ranks, inspiring your troops.',
    probability: 0.03,
    effects: { militaryBonus: 1.2 },
    duration: 8,
    conditions: { hasBuilding: 'barracks' },
  },
  {
    id: 'pirate_activity',
    name: 'Pirate Activity',
    type: EVENT_TYPES.MILITARY,
    icon: '🏴‍☠️',
    description: 'Pirates threaten your trade routes! Maritime commerce is disrupted.',
    probability: 0.04,
    effects: { tradeMultiplier: 0.7 },
    duration: 4,
    conditions: { hasBuilding: 'port' },
  },
  {
    id: 'resource_discovery',
    name: 'Resource Discovery',
    type: EVENT_TYPES.DISCOVERY,
    icon: '🔍',
    description: 'Surveyors have discovered new {resourceType} deposits in {territory}!',
    probability: 0.04,
    effects: { addRandomResource: true },
    duration: 1,
    conditions: {},
  },
  {
    id: 'industrial_accident',
    name: 'Industrial Accident',
    type: EVENT_TYPES.ECONOMIC,
    icon: '🔥',
    description: 'An explosion at a factory in {territory} halts production.',
    probability: 0.03,
    effects: { factoryShutdown: true, stability: -3 },
    duration: 2,
    conditions: { hasBuilding: 'foundry' },
  },
  {
    id: 'cultural_renaissance',
    name: 'Cultural Renaissance',
    type: EVENT_TYPES.CULTURAL,
    icon: '🎨',
    description: 'A flourishing of arts and culture sweeps across your empire!',
    probability: 0.02,
    effects: { stability: 10, diplomacyBonus: 5, researchBonus: 5 },
    duration: 6,
    conditions: { stabilityAbove: 60 },
  },
  {
    id: 'migration_wave',
    name: 'Immigration Wave',
    type: EVENT_TYPES.POLITICAL,
    icon: '👥',
    description: 'People flock to your nation seeking a better life.',
    probability: 0.03,
    effects: { population: 1.15, workerGain: 2, stability: -2 },
    duration: 1,
    conditions: { stabilityAbove: 50 },
  },
];
