export const AI_PERSONALITY = {
  EXPANSIONIST: 'expansionist',
  MERCHANT: 'merchant',
  MILITARIST: 'militarist',
  DIPLOMAT: 'diplomat',
  INDUSTRIALIST: 'industrialist',
  ISOLATIONIST: 'isolationist',
  OPPORTUNIST: 'opportunist',
};

export const NATION_TEMPLATES = [
  {
    id: 'britannia',
    name: 'Britannia',
    color: '#c41e3a',
    secondaryColor: '#ffffff',
    flag: '🇬🇧',
    personality: AI_PERSONALITY.MERCHANT,
    traits: {
      naval: 1.3,
      trade: 1.4,
      diplomacy: 1.1,
      military: 1.0,
      industry: 1.2,
      expansion: 1.1,
      aggression: 0.7,
    },
    description: 'A mighty naval and trading empire. Masters of the seas and commerce.',
    bonuses: ['naval_tradition', 'free_trade'],
  },
  {
    id: 'francia',
    name: 'Francia',
    color: '#0055a4',
    secondaryColor: '#ffffff',
    flag: '🇫🇷',
    personality: AI_PERSONALITY.MILITARIST,
    traits: {
      naval: 1.0,
      trade: 1.0,
      diplomacy: 1.1,
      military: 1.4,
      industry: 1.1,
      expansion: 1.2,
      aggression: 1.1,
    },
    description: 'A proud continental power with a formidable army and rich culture.',
    bonuses: ['grande_armee', 'cultural_influence'],
  },
  {
    id: 'germania',
    name: 'Germania',
    color: '#2c2c2c',
    secondaryColor: '#d4a600',
    flag: '🇩🇪',
    personality: AI_PERSONALITY.INDUSTRIALIST,
    traits: {
      naval: 0.9,
      trade: 1.1,
      diplomacy: 0.8,
      military: 1.3,
      industry: 1.5,
      expansion: 1.0,
      aggression: 1.0,
    },
    description: 'An industrial juggernaut with disciplined military forces.',
    bonuses: ['industrial_revolution', 'iron_discipline'],
  },
  {
    id: 'russland',
    name: 'Russland',
    color: '#1c3f6e',
    secondaryColor: '#c8102e',
    flag: '🇷🇺',
    personality: AI_PERSONALITY.EXPANSIONIST,
    traits: {
      naval: 0.7,
      trade: 0.8,
      diplomacy: 0.8,
      military: 1.2,
      industry: 0.9,
      expansion: 1.6,
      aggression: 1.2,
    },
    description: 'A vast empire with endless manpower and territorial ambitions.',
    bonuses: ['endless_manpower', 'winter_warfare'],
  },
  {
    id: 'ottoman',
    name: 'Ottomana',
    color: '#c41e3a',
    secondaryColor: '#1a472a',
    flag: '🇹🇷',
    personality: AI_PERSONALITY.DIPLOMAT,
    traits: {
      naval: 1.0,
      trade: 1.3,
      diplomacy: 1.4,
      military: 1.1,
      industry: 0.9,
      expansion: 1.0,
      aggression: 0.8,
    },
    description: 'A crossroads empire bridging continents, skilled in diplomacy and trade.',
    bonuses: ['crossroads_of_world', 'grand_bazaar'],
  },
  {
    id: 'nihon',
    name: 'Nihon',
    color: '#bc002d',
    secondaryColor: '#ffffff',
    flag: '🇯🇵',
    personality: AI_PERSONALITY.ISOLATIONIST,
    traits: {
      naval: 1.2,
      trade: 0.9,
      diplomacy: 0.7,
      military: 1.3,
      industry: 1.2,
      expansion: 0.8,
      aggression: 0.6,
    },
    description: 'An island nation with a warrior tradition and rapid modernization.',
    bonuses: ['bushido', 'rapid_modernization'],
  },
  {
    id: 'americana',
    name: 'Americana',
    color: '#002868',
    secondaryColor: '#bf0a30',
    flag: '🇺🇸',
    personality: AI_PERSONALITY.OPPORTUNIST,
    traits: {
      naval: 1.1,
      trade: 1.3,
      diplomacy: 1.0,
      military: 1.1,
      industry: 1.4,
      expansion: 1.3,
      aggression: 0.9,
    },
    description: 'A young and ambitious nation with boundless resources and opportunity.',
    bonuses: ['manifest_destiny', 'melting_pot'],
  },
  {
    id: 'hispania',
    name: 'Hispania',
    color: '#aa151b',
    secondaryColor: '#f1bf00',
    flag: '🇪🇸',
    personality: AI_PERSONALITY.EXPANSIONIST,
    traits: {
      naval: 1.2,
      trade: 1.1,
      diplomacy: 0.9,
      military: 1.0,
      industry: 0.8,
      expansion: 1.4,
      aggression: 1.0,
    },
    description: 'A colonial empire with a legacy of exploration and conquest.',
    bonuses: ['conquistadors', 'colonial_legacy'],
  },
];

export const MINOR_NATION_TEMPLATES = [
  { id: 'minor_tropical', name: 'Tropical Kingdom', color: '#2ecc71', personality: 'neutral' },
  { id: 'minor_desert', name: 'Desert Sultanate', color: '#e67e22', personality: 'defensive' },
  { id: 'minor_island', name: 'Island Republic', color: '#3498db', personality: 'trading' },
  { id: 'minor_mountain', name: 'Mountain Confederation', color: '#95a5a6', personality: 'defensive' },
  { id: 'minor_forest', name: 'Forest Tribes', color: '#27ae60', personality: 'aggressive' },
  { id: 'minor_steppe', name: 'Steppe Khanate', color: '#8e44ad', personality: 'aggressive' },
];
