export const RESOURCE_CATEGORY = {
  RAW: 'raw',
  PROCESSED: 'processed',
  LUXURY: 'luxury',
  MILITARY: 'military',
  FOOD: 'food',
};

export const RESOURCES = {
  // Food & Agriculture
  grain: {
    id: 'grain',
    name: 'Grain',
    icon: '🌾',
    category: RESOURCE_CATEGORY.FOOD,
    baseValue: 2,
    description: 'Staple food for your population',
  },
  cattle: {
    id: 'cattle',
    name: 'Cattle',
    icon: '🐄',
    category: RESOURCE_CATEGORY.FOOD,
    baseValue: 4,
    description: 'Livestock for food and leather',
  },
  fish: {
    id: 'fish',
    name: 'Fish',
    icon: '🐟',
    category: RESOURCE_CATEGORY.FOOD,
    baseValue: 3,
    description: 'Harvested from coastal and river tiles',
  },
  // Raw Materials
  timber: {
    id: 'timber',
    name: 'Timber',
    icon: '🪵',
    category: RESOURCE_CATEGORY.RAW,
    baseValue: 3,
    description: 'Essential building material',
  },
  iron: {
    id: 'iron',
    name: 'Iron',
    icon: '⛏️',
    category: RESOURCE_CATEGORY.RAW,
    baseValue: 5,
    description: 'Critical for industry and military',
  },
  coal: {
    id: 'coal',
    name: 'Coal',
    icon: '⬛',
    category: RESOURCE_CATEGORY.RAW,
    baseValue: 4,
    description: 'Fuel for industry and railroads',
  },
  stone: {
    id: 'stone',
    name: 'Stone',
    icon: '🪨',
    category: RESOURCE_CATEGORY.RAW,
    baseValue: 2,
    description: 'Building material for fortifications',
  },
  cotton: {
    id: 'cotton',
    name: 'Cotton',
    icon: '☁️',
    category: RESOURCE_CATEGORY.RAW,
    baseValue: 3,
    description: 'Raw material for textiles',
  },
  wool: {
    id: 'wool',
    name: 'Wool',
    icon: '🐑',
    category: RESOURCE_CATEGORY.RAW,
    baseValue: 3,
    description: 'From grazing livestock, used for textiles',
  },
  rubber: {
    id: 'rubber',
    name: 'Rubber',
    icon: '⚫',
    category: RESOURCE_CATEGORY.RAW,
    baseValue: 6,
    description: 'Strategic resource for advanced industry',
  },
  oil: {
    id: 'oil',
    name: 'Oil',
    icon: '🛢️',
    category: RESOURCE_CATEGORY.RAW,
    baseValue: 8,
    description: 'Black gold - fuel of the modern age',
  },
  peat: {
    id: 'peat',
    name: 'Peat',
    icon: '🟤',
    category: RESOURCE_CATEGORY.RAW,
    baseValue: 2,
    description: 'Primitive fuel source from wetlands',
  },
  // Processed goods
  steel: {
    id: 'steel',
    name: 'Steel',
    icon: '🔩',
    category: RESOURCE_CATEGORY.PROCESSED,
    baseValue: 10,
    recipe: { iron: 2, coal: 1 },
    description: 'Refined metal for construction and weapons',
  },
  textiles: {
    id: 'textiles',
    name: 'Textiles',
    icon: '🧵',
    category: RESOURCE_CATEGORY.PROCESSED,
    baseValue: 8,
    recipe: { cotton: 2 },
    altRecipe: { wool: 2 },
    description: 'Manufactured cloth and garments',
  },
  lumber: {
    id: 'lumber',
    name: 'Lumber',
    icon: '🪓',
    category: RESOURCE_CATEGORY.PROCESSED,
    baseValue: 6,
    recipe: { timber: 2 },
    description: 'Processed wood for construction',
  },
  arms: {
    id: 'arms',
    name: 'Arms',
    icon: '⚔️',
    category: RESOURCE_CATEGORY.MILITARY,
    baseValue: 15,
    recipe: { steel: 1, timber: 1 },
    description: 'Weapons and ammunition for military units',
  },
  munitions: {
    id: 'munitions',
    name: 'Munitions',
    icon: '💣',
    category: RESOURCE_CATEGORY.MILITARY,
    baseValue: 12,
    recipe: { steel: 1, coal: 1 },
    description: 'Explosive ordnance for artillery',
  },
  // Luxury & Trade goods
  gold: {
    id: 'gold',
    name: 'Gold',
    icon: '🥇',
    category: RESOURCE_CATEGORY.LUXURY,
    baseValue: 20,
    description: 'Precious metal, universal currency',
  },
  silver: {
    id: 'silver',
    name: 'Silver',
    icon: '🥈',
    category: RESOURCE_CATEGORY.LUXURY,
    baseValue: 12,
    description: 'Precious metal for trade and currency',
  },
  gems: {
    id: 'gems',
    name: 'Gems',
    icon: '💎',
    category: RESOURCE_CATEGORY.LUXURY,
    baseValue: 25,
    description: 'Precious stones of immense value',
  },
  spices: {
    id: 'spices',
    name: 'Spices',
    icon: '🌶️',
    category: RESOURCE_CATEGORY.LUXURY,
    baseValue: 15,
    description: 'Exotic spices from distant lands',
  },
  fur: {
    id: 'fur',
    name: 'Fur',
    icon: '🦊',
    category: RESOURCE_CATEGORY.LUXURY,
    baseValue: 10,
    description: 'Valuable pelts from northern forests',
  },
  ivory: {
    id: 'ivory',
    name: 'Ivory',
    icon: '🦷',
    category: RESOURCE_CATEGORY.LUXURY,
    baseValue: 18,
    description: 'Exotic trade good from the savanna',
  },
  pearls: {
    id: 'pearls',
    name: 'Pearls',
    icon: '🫧',
    category: RESOURCE_CATEGORY.LUXURY,
    baseValue: 16,
    description: 'Rare treasures from coastal waters',
  },
  herbs: {
    id: 'herbs',
    name: 'Herbs',
    icon: '🌿',
    category: RESOURCE_CATEGORY.LUXURY,
    baseValue: 5,
    description: 'Medicinal and culinary plants',
  },
  horses: {
    id: 'horses',
    name: 'Horses',
    icon: '🐴',
    category: RESOURCE_CATEGORY.MILITARY,
    baseValue: 8,
    description: 'Essential for cavalry and transport',
  },
};

export const RESOURCE_LIST = Object.values(RESOURCES);

export const getResourceById = (id) => RESOURCES[id];

export const getResourcesByCategory = (category) =>
  RESOURCE_LIST.filter(r => r.category === category);
