export const TECH_CATEGORIES = {
  MILITARY: 'military',
  ECONOMY: 'economy',
  NAVAL: 'naval',
  CULTURE: 'culture',
  INDUSTRY: 'industry',
};

export const TECHNOLOGIES = {
  // Tier 1 - Starting Era
  agriculture: {
    id: 'agriculture',
    name: 'Advanced Agriculture',
    category: TECH_CATEGORIES.ECONOMY,
    tier: 1,
    cost: 30,
    prerequisites: [],
    effects: { farmOutput: 1.25 },
    description: 'Improved farming techniques increase grain output by 25%',
  },
  basic_mining: {
    id: 'basic_mining',
    name: 'Mining Techniques',
    category: TECH_CATEGORIES.INDUSTRY,
    tier: 1,
    cost: 30,
    prerequisites: [],
    effects: { mineOutput: 1.25 },
    description: 'Better extraction methods increase mineral yields',
  },
  sailing: {
    id: 'sailing',
    name: 'Improved Sailing',
    category: TECH_CATEGORIES.NAVAL,
    tier: 1,
    cost: 25,
    prerequisites: [],
    effects: { navalSpeed: 1.2 },
    description: 'Better rigging and navigation improve ship speed',
  },
  conscription: {
    id: 'conscription',
    name: 'Conscription',
    category: TECH_CATEGORIES.MILITARY,
    tier: 1,
    cost: 25,
    prerequisites: [],
    effects: { recruitSpeed: 1.25, militiaCost: 0.75 },
    description: 'Organized conscription produces troops faster and cheaper',
  },
  education: {
    id: 'education',
    name: 'Public Education',
    category: TECH_CATEGORIES.CULTURE,
    tier: 1,
    cost: 35,
    prerequisites: [],
    effects: { researchRate: 1.2 },
    unlocks: ['university'],
    description: 'Establishes public schooling, unlocks universities',
  },

  // Tier 2
  rifling: {
    id: 'rifling',
    name: 'Rifled Barrels',
    category: TECH_CATEGORIES.MILITARY,
    tier: 2,
    cost: 50,
    prerequisites: ['basic_mining'],
    effects: { infantryAttack: 1.3 },
    unlocks: ['riflemen'],
    description: 'Rifled weapons dramatically improve infantry accuracy',
  },
  steam_power: {
    id: 'steam_power',
    name: 'Steam Power',
    category: TECH_CATEGORIES.INDUSTRY,
    tier: 2,
    cost: 60,
    prerequisites: ['basic_mining'],
    effects: { factoryOutput: 1.3 },
    description: 'Steam engines revolutionize industrial production',
  },
  navigation: {
    id: 'navigation',
    name: 'Advanced Navigation',
    category: TECH_CATEGORIES.NAVAL,
    tier: 2,
    cost: 40,
    prerequisites: ['sailing'],
    effects: { navalRange: 1.3, explorationSpeed: 1.5 },
    description: 'Sextants and charts enable longer voyages',
  },
  banking: {
    id: 'banking',
    name: 'Banking System',
    category: TECH_CATEGORIES.ECONOMY,
    tier: 2,
    cost: 45,
    prerequisites: ['education'],
    effects: { goldIncome: 1.2, tradeValue: 1.15 },
    description: 'Organized banking improves treasury income and trade',
  },
  fortification: {
    id: 'fortification',
    name: 'Modern Fortifications',
    category: TECH_CATEGORIES.MILITARY,
    tier: 2,
    cost: 45,
    prerequisites: ['conscription'],
    effects: { fortDefense: 1.5 },
    description: 'Star forts and bastions greatly improve defensive positions',
  },

  // Tier 3
  railroads: {
    id: 'railroads',
    name: 'Railroads',
    category: TECH_CATEGORIES.INDUSTRY,
    tier: 3,
    cost: 80,
    prerequisites: ['steam_power'],
    effects: { movementSpeed: 1.5, resourceTransport: 1.5 },
    unlocks: ['railroad'],
    description: 'Rail networks transform logistics and economic output',
  },
  ironclad_ships: {
    id: 'ironclad_ships',
    name: 'Ironclad Warships',
    category: TECH_CATEGORIES.NAVAL,
    tier: 3,
    cost: 90,
    prerequisites: ['steam_power', 'navigation'],
    effects: { navalPower: 1.5 },
    unlocks: ['ironclad'],
    description: 'Armor-plated steam warships dominate the seas',
  },
  elite_training: {
    id: 'elite_training',
    name: 'Elite Military Training',
    category: TECH_CATEGORIES.MILITARY,
    tier: 3,
    cost: 70,
    prerequisites: ['rifling', 'fortification'],
    effects: { unitExperience: 1.5 },
    unlocks: ['guards'],
    description: 'Professional military academies produce elite soldiers',
  },
  free_trade: {
    id: 'free_trade',
    name: 'Free Trade Policies',
    category: TECH_CATEGORIES.ECONOMY,
    tier: 3,
    cost: 65,
    prerequisites: ['banking'],
    effects: { tradeValue: 1.3, diplomacyBonus: 5 },
    description: 'Open markets boost trade revenue and diplomatic relations',
  },
  oil_drilling: {
    id: 'oil_drilling',
    name: 'Oil Drilling',
    category: TECH_CATEGORIES.INDUSTRY,
    tier: 3,
    cost: 75,
    prerequisites: ['steam_power', 'basic_mining'],
    unlocks: ['oil_well'],
    description: 'Extract petroleum, the fuel of the future',
  },
  journalism: {
    id: 'journalism',
    name: 'Free Press',
    category: TECH_CATEGORIES.CULTURE,
    tier: 3,
    cost: 55,
    prerequisites: ['education'],
    effects: { stabilityBonus: 5, espionageDefense: 1.2 },
    description: 'A free press improves stability and reveals threats',
  },

  // Tier 4
  mass_production: {
    id: 'mass_production',
    name: 'Mass Production',
    category: TECH_CATEGORIES.INDUSTRY,
    tier: 4,
    cost: 120,
    prerequisites: ['railroads'],
    effects: { factoryOutput: 1.5, unitCost: 0.8 },
    description: 'Assembly lines slash production costs dramatically',
  },
  combined_arms: {
    id: 'combined_arms',
    name: 'Combined Arms Doctrine',
    category: TECH_CATEGORIES.MILITARY,
    tier: 4,
    cost: 100,
    prerequisites: ['elite_training', 'railroads'],
    effects: { armyCoordination: 1.4, combatEfficiency: 1.3 },
    description: 'Infantry, cavalry, and artillery fight as one',
  },
  global_trade: {
    id: 'global_trade',
    name: 'Global Trade Networks',
    category: TECH_CATEGORIES.ECONOMY,
    tier: 4,
    cost: 110,
    prerequisites: ['free_trade', 'railroads'],
    effects: { tradeValue: 1.5, portIncome: 2.0 },
    description: 'Worldwide trade routes generate enormous wealth',
  },
  nationalism: {
    id: 'nationalism',
    name: 'Nationalism',
    category: TECH_CATEGORIES.CULTURE,
    tier: 4,
    cost: 80,
    prerequisites: ['journalism'],
    effects: { stability: 10, militaryMorale: 1.3, diplomacyPenalty: -5 },
    description: 'National pride boosts morale but strains diplomacy',
  },
};

export const TECH_LIST = Object.values(TECHNOLOGIES);
export const getTechById = (id) => TECHNOLOGIES[id];
export const getAvailableTechs = (researched) =>
  TECH_LIST.filter(t =>
    !researched.includes(t.id) &&
    t.prerequisites.every(p => researched.includes(p))
  );
