export const TERRAIN = {
  DEEP_OCEAN: {
    id: 'deep_ocean',
    name: 'Deep Ocean',
    color: '#1a3a5c',
    moveCost: 2,
    defense: 0,
    buildable: false,
    naval: true,
    resources: [],
    description: 'Deep waters, navigable by ocean-going vessels',
  },
  OCEAN: {
    id: 'ocean',
    name: 'Ocean',
    color: '#2a5a8c',
    moveCost: 1,
    defense: 0,
    buildable: false,
    naval: true,
    resources: ['fish'],
    description: 'Open waters rich with marine life',
  },
  COAST: {
    id: 'coast',
    name: 'Coastal Waters',
    color: '#4a8ab4',
    moveCost: 1,
    defense: 0,
    buildable: false,
    naval: true,
    resources: ['fish', 'pearls'],
    description: 'Shallow coastal waters, ideal for fishing',
  },
  PLAINS: {
    id: 'plains',
    name: 'Plains',
    color: '#c4b550',
    moveCost: 1,
    defense: 0,
    buildable: true,
    naval: false,
    resources: ['grain', 'horses'],
    description: 'Flat, fertile lands perfect for farming',
  },
  GRASSLAND: {
    id: 'grassland',
    name: 'Grassland',
    color: '#7ab648',
    moveCost: 1,
    defense: 0,
    buildable: true,
    naval: false,
    resources: ['grain', 'cattle', 'wool'],
    description: 'Lush green pastures for grazing and agriculture',
  },
  FOREST: {
    id: 'forest',
    name: 'Forest',
    color: '#2d6e2d',
    moveCost: 2,
    defense: 2,
    buildable: true,
    naval: false,
    resources: ['timber', 'fur', 'herbs'],
    description: 'Dense woodland providing timber and shelter',
  },
  JUNGLE: {
    id: 'jungle',
    name: 'Jungle',
    color: '#1a5c1a',
    moveCost: 3,
    defense: 3,
    buildable: true,
    naval: false,
    resources: ['timber', 'spices', 'rubber', 'gems'],
    description: 'Thick tropical jungle, hard to traverse but resource-rich',
  },
  HILLS: {
    id: 'hills',
    name: 'Hills',
    color: '#8b7d4a',
    moveCost: 2,
    defense: 2,
    buildable: true,
    naval: false,
    resources: ['iron', 'coal', 'stone'],
    description: 'Rolling hills with mineral deposits',
  },
  MOUNTAINS: {
    id: 'mountains',
    name: 'Mountains',
    color: '#6e6e6e',
    moveCost: 4,
    defense: 4,
    buildable: false,
    naval: false,
    resources: ['gold', 'silver', 'gems', 'iron'],
    description: 'Towering peaks, impassable but rich in precious metals',
  },
  DESERT: {
    id: 'desert',
    name: 'Desert',
    color: '#d4b96a',
    moveCost: 2,
    defense: 0,
    buildable: true,
    naval: false,
    resources: ['oil', 'gold'],
    description: 'Arid wasteland with hidden riches beneath the sands',
  },
  TUNDRA: {
    id: 'tundra',
    name: 'Tundra',
    color: '#a0b8c0',
    moveCost: 2,
    defense: 1,
    buildable: true,
    naval: false,
    resources: ['fur', 'oil', 'iron'],
    description: 'Frozen northern lands with hardy resources',
  },
  SWAMP: {
    id: 'swamp',
    name: 'Swamp',
    color: '#4a6e3a',
    moveCost: 3,
    defense: 2,
    buildable: true,
    naval: false,
    resources: ['herbs', 'peat'],
    description: 'Boggy wetlands, difficult terrain but unique resources',
  },
  SAVANNA: {
    id: 'savanna',
    name: 'Savanna',
    color: '#c8a840',
    moveCost: 1,
    defense: 0,
    buildable: true,
    naval: false,
    resources: ['grain', 'cattle', 'ivory'],
    description: 'Wide open grasslands with scattered trees',
  },
  RIVER: {
    id: 'river',
    name: 'River',
    color: '#5090c0',
    moveCost: 1,
    defense: 1,
    buildable: true,
    naval: false,
    resources: ['fish', 'grain'],
    description: 'Fertile riverbanks ideal for settlement',
  },
};

export const TERRAIN_LIST = Object.values(TERRAIN);

export const getTerrainById = (id) => {
  return TERRAIN_LIST.find(t => t.id === id);
};
