export const UNIT_CATEGORY = {
  LAND: 'land',
  NAVAL: 'naval',
};

export const UNITS = {
  // Land Units
  militia: {
    id: 'militia',
    name: 'Militia',
    category: UNIT_CATEGORY.LAND,
    icon: '🗡️',
    attack: 2,
    defense: 3,
    hp: 80,
    movement: 2,
    upkeep: 1,
    cost: { gold: 20 },
    recruitTime: 1,
    description: 'Cheap defensive force recruited from the populace',
  },
  infantry: {
    id: 'infantry',
    name: 'Infantry',
    category: UNIT_CATEGORY.LAND,
    icon: '🔫',
    attack: 5,
    defense: 4,
    hp: 100,
    movement: 2,
    upkeep: 3,
    cost: { gold: 50, arms: 1 },
    recruitTime: 2,
    description: 'Standard line infantry, backbone of any army',
  },
  cavalry: {
    id: 'cavalry',
    name: 'Cavalry',
    category: UNIT_CATEGORY.LAND,
    icon: '🐎',
    attack: 7,
    defense: 3,
    hp: 90,
    movement: 4,
    upkeep: 4,
    cost: { gold: 80, arms: 1, horses: 1 },
    recruitTime: 2,
    description: 'Fast-moving mounted troops, excellent for flanking',
  },
  artillery: {
    id: 'artillery',
    name: 'Artillery',
    category: UNIT_CATEGORY.LAND,
    icon: '💥',
    attack: 10,
    defense: 1,
    hp: 60,
    movement: 1,
    upkeep: 5,
    cost: { gold: 100, steel: 1, munitions: 1 },
    recruitTime: 3,
    description: 'Devastating ranged firepower, slow but powerful',
  },
  engineer: {
    id: 'engineer',
    name: 'Engineer',
    category: UNIT_CATEGORY.LAND,
    icon: '⚒️',
    attack: 1,
    defense: 2,
    hp: 70,
    movement: 2,
    upkeep: 2,
    cost: { gold: 40 },
    recruitTime: 2,
    canBuild: true,
    description: 'Builds roads, railroads, forts, and other improvements',
  },
  guards: {
    id: 'guards',
    name: 'Imperial Guards',
    category: UNIT_CATEGORY.LAND,
    icon: '🛡️',
    attack: 8,
    defense: 8,
    hp: 130,
    movement: 2,
    upkeep: 8,
    cost: { gold: 150, arms: 2, steel: 1 },
    recruitTime: 4,
    requiresTech: 'elite_training',
    description: 'Elite professional soldiers, the finest in the empire',
  },
  riflemen: {
    id: 'riflemen',
    name: 'Riflemen',
    category: UNIT_CATEGORY.LAND,
    icon: '🎯',
    attack: 7,
    defense: 5,
    hp: 100,
    movement: 2,
    upkeep: 4,
    cost: { gold: 70, arms: 1 },
    recruitTime: 2,
    requiresTech: 'rifling',
    description: 'Accurate shooters with superior range',
  },
  // Naval Units
  sloop: {
    id: 'sloop',
    name: 'Sloop',
    category: UNIT_CATEGORY.NAVAL,
    icon: '⛵',
    attack: 2,
    defense: 2,
    hp: 60,
    movement: 4,
    upkeep: 2,
    cost: { gold: 40, lumber: 1 },
    recruitTime: 2,
    description: 'Light patrol vessel for coastal defense',
  },
  frigate: {
    id: 'frigate',
    name: 'Frigate',
    category: UNIT_CATEGORY.NAVAL,
    icon: '🚢',
    attack: 5,
    defense: 4,
    hp: 100,
    movement: 3,
    upkeep: 4,
    cost: { gold: 80, lumber: 2, arms: 1 },
    recruitTime: 3,
    description: 'Versatile warship, the workhorse of the navy',
  },
  ship_of_line: {
    id: 'ship_of_line',
    name: 'Ship of the Line',
    category: UNIT_CATEGORY.NAVAL,
    icon: '⚓',
    attack: 10,
    defense: 8,
    hp: 160,
    movement: 2,
    upkeep: 8,
    cost: { gold: 160, lumber: 3, arms: 2, steel: 1 },
    recruitTime: 5,
    description: 'Massive warship bristling with cannons',
  },
  transport: {
    id: 'transport',
    name: 'Transport',
    category: UNIT_CATEGORY.NAVAL,
    icon: '🛳️',
    attack: 0,
    defense: 2,
    hp: 80,
    movement: 3,
    upkeep: 2,
    cost: { gold: 50, lumber: 2 },
    recruitTime: 2,
    capacity: 3,
    description: 'Carries land units across the seas',
  },
  ironclad: {
    id: 'ironclad',
    name: 'Ironclad',
    category: UNIT_CATEGORY.NAVAL,
    icon: '🛡️',
    attack: 12,
    defense: 12,
    hp: 200,
    movement: 2,
    upkeep: 10,
    cost: { gold: 250, steel: 3, coal: 2, arms: 2 },
    recruitTime: 6,
    requiresTech: 'ironclad_ships',
    description: 'Steam-powered armored warship, nearly unstoppable',
  },
};

export const UNIT_LIST = Object.values(UNITS);
export const LAND_UNITS = UNIT_LIST.filter(u => u.category === UNIT_CATEGORY.LAND);
export const NAVAL_UNITS = UNIT_LIST.filter(u => u.category === UNIT_CATEGORY.NAVAL);
